# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageServiceStream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18ImageServiceStream.proto\x12\x0bimagestream\"#\n\x12ImagePromptMessage\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2W\n\x12ImageStreamService\x12\x41\n\nClientSend\x12\x1f.imagestream.ImagePromptMessage\x1a\x10.imagestream.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImageServiceStream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEPROMPTMESSAGE']._serialized_start=41
  _globals['_IMAGEPROMPTMESSAGE']._serialized_end=76
  _globals['_ACK']._serialized_start=78
  _globals['_ACK']._serialized_end=99
  _globals['_IMAGESTREAMSERVICE']._serialized_start=101
  _globals['_IMAGESTREAMSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
