# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebChatService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WebChatService.proto\x12\x0ewebchatservice\"\x1f\n\x0b\x43hatMessage\x12\x10\n\x08response\x18\x01 \x01(\t\"%\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\x0bTextMessage\x12\x0e\n\x06prompt\x18\x01 \x01(\t2\xa5\x01\n\x14WebChatStreamService\x12>\n\nClientSend\x12\x1b.webchatservice.TextMessage\x1a\x13.webchatservice.Ack\x12M\n\nServerSend\x12 .webchatservice.SubscribeRequest\x1a\x1b.webchatservice.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebChatService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=40
  _globals['_CHATMESSAGE']._serialized_end=71
  _globals['_SUBSCRIBEREQUEST']._serialized_start=73
  _globals['_SUBSCRIBEREQUEST']._serialized_end=110
  _globals['_ACK']._serialized_start=112
  _globals['_ACK']._serialized_end=133
  _globals['_TEXTMESSAGE']._serialized_start=135
  _globals['_TEXTMESSAGE']._serialized_end=164
  _globals['_WEBCHATSTREAMSERVICE']._serialized_start=167
  _globals['_WEBCHATSTREAMSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
