# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import AgentServiceStream_pb2 as AgentServiceStream__pb2


class AgentStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSend = channel.stream_unary(
                '/agentstream.AgentStreamService/ClientSend',
                request_serializer=AgentServiceStream__pb2.ImagePromptMessage.SerializeToString,
                response_deserializer=AgentServiceStream__pb2.Ack.FromString,
                )
        self.ServerSend = channel.unary_stream(
                '/agentstream.AgentStreamService/ServerSend',
                request_serializer=AgentServiceStream__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=AgentServiceStream__pb2.TextResultMessage.FromString,
                )


class AgentStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientSend(self, request_iterator, context):
        """Client streams image + prompt to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerSend(self, request, context):
        """Client subscribes to textual results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSend': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientSend,
                    request_deserializer=AgentServiceStream__pb2.ImagePromptMessage.FromString,
                    response_serializer=AgentServiceStream__pb2.Ack.SerializeToString,
            ),
            'ServerSend': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerSend,
                    request_deserializer=AgentServiceStream__pb2.SubscribeRequest.FromString,
                    response_serializer=AgentServiceStream__pb2.TextResultMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentstream.AgentStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientSend(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/agentstream.AgentStreamService/ClientSend',
            AgentServiceStream__pb2.ImagePromptMessage.SerializeToString,
            AgentServiceStream__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/agentstream.AgentStreamService/ServerSend',
            AgentServiceStream__pb2.SubscribeRequest.SerializeToString,
            AgentServiceStream__pb2.TextResultMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
