# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebChatService_pb2 as WebChatService__pb2


class WebChatStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSend = channel.unary_unary(
                '/webchatservice.WebChatStreamService/ClientSend',
                request_serializer=WebChatService__pb2.TextMessage.SerializeToString,
                response_deserializer=WebChatService__pb2.Ack.FromString,
                )
        self.ServerSend = channel.unary_stream(
                '/webchatservice.WebChatStreamService/ServerSend',
                request_serializer=WebChatService__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=WebChatService__pb2.ChatMessage.FromString,
                )


class WebChatStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebChatStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSend': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSend,
                    request_deserializer=WebChatService__pb2.TextMessage.FromString,
                    response_serializer=WebChatService__pb2.Ack.SerializeToString,
            ),
            'ServerSend': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerSend,
                    request_deserializer=WebChatService__pb2.SubscribeRequest.FromString,
                    response_serializer=WebChatService__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webchatservice.WebChatStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebChatStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webchatservice.WebChatStreamService/ClientSend',
            WebChatService__pb2.TextMessage.SerializeToString,
            WebChatService__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/webchatservice.WebChatStreamService/ServerSend',
            WebChatService__pb2.SubscribeRequest.SerializeToString,
            WebChatService__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
