# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebImageService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15WebImageService.proto\x12\x0ewebimagestream\"\x1d\n\x0cImageMessage\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2_\n\x15WebImageStreamService\x12\x46\n\x0fSendImageStream\x12\x1c.webimagestream.ImageMessage\x1a\x13.webimagestream.Ack(\x01\x32[\n\x14WebImageEventService\x12\x43\n\x0eSendImageEvent\x12\x1c.webimagestream.ImageMessage\x1a\x13.webimagestream.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WebImageService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEMESSAGE']._serialized_start=41
  _globals['_IMAGEMESSAGE']._serialized_end=70
  _globals['_ACK']._serialized_start=72
  _globals['_ACK']._serialized_end=93
  _globals['_WEBIMAGESTREAMSERVICE']._serialized_start=95
  _globals['_WEBIMAGESTREAMSERVICE']._serialized_end=190
  _globals['_WEBIMAGEEVENTSERVICE']._serialized_start=192
  _globals['_WEBIMAGEEVENTSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
