# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebImageService_pb2 as WebImageService__pb2


class WebImageStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendImageStream = channel.stream_unary(
                '/webimagestream.WebImageStreamService/SendImageStream',
                request_serializer=WebImageService__pb2.ImageMessage.SerializeToString,
                response_deserializer=WebImageService__pb2.Ack.FromString,
                )


class WebImageStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendImageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebImageStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendImageStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendImageStream,
                    request_deserializer=WebImageService__pb2.ImageMessage.FromString,
                    response_serializer=WebImageService__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webimagestream.WebImageStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebImageStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendImageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/webimagestream.WebImageStreamService/SendImageStream',
            WebImageService__pb2.ImageMessage.SerializeToString,
            WebImageService__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class WebImageEventServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendImageEvent = channel.unary_unary(
                '/webimagestream.WebImageEventService/SendImageEvent',
                request_serializer=WebImageService__pb2.ImageMessage.SerializeToString,
                response_deserializer=WebImageService__pb2.Ack.FromString,
                )


class WebImageEventServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendImageEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebImageEventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendImageEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendImageEvent,
                    request_deserializer=WebImageService__pb2.ImageMessage.FromString,
                    response_serializer=WebImageService__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'webimagestream.WebImageEventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WebImageEventService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendImageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/webimagestream.WebImageEventService/SendImageEvent',
            WebImageService__pb2.ImageMessage.SerializeToString,
            WebImageService__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
