# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: STTServiceStream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16STTServiceStream.proto\x12\tsttstream\"\x1c\n\rStatusMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1e\n\nSTTMessage\x12\x10\n\x08response\x18\x01 \x01(\t\"%\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t2\x90\x01\n\x10STTStreamService\x12\x38\n\nClientSend\x12\x18.sttstream.StatusMessage\x1a\x0e.sttstream.Ack(\x01\x12\x42\n\nServerSend\x12\x1b.sttstream.SubscribeRequest\x1a\x15.sttstream.STTMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'STTServiceStream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSMESSAGE']._serialized_start=37
  _globals['_STATUSMESSAGE']._serialized_end=65
  _globals['_STTMESSAGE']._serialized_start=67
  _globals['_STTMESSAGE']._serialized_end=97
  _globals['_SUBSCRIBEREQUEST']._serialized_start=99
  _globals['_SUBSCRIBEREQUEST']._serialized_end=136
  _globals['_ACK']._serialized_start=138
  _globals['_ACK']._serialized_end=159
  _globals['_STTSTREAMSERVICE']._serialized_start=162
  _globals['_STTSTREAMSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
