# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import STTServiceStream_pb2 as STTServiceStream__pb2


class STTStreamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSend = channel.stream_unary(
                '/sttstream.STTStreamService/ClientSend',
                request_serializer=STTServiceStream__pb2.StatusMessage.SerializeToString,
                response_deserializer=STTServiceStream__pb2.Ack.FromString,
                )
        self.ServerSend = channel.unary_stream(
                '/sttstream.STTStreamService/ServerSend',
                request_serializer=STTServiceStream__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=STTServiceStream__pb2.STTMessage.FromString,
                )


class STTStreamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientSend(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerSend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSend': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientSend,
                    request_deserializer=STTServiceStream__pb2.StatusMessage.FromString,
                    response_serializer=STTServiceStream__pb2.Ack.SerializeToString,
            ),
            'ServerSend': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerSend,
                    request_deserializer=STTServiceStream__pb2.SubscribeRequest.FromString,
                    response_serializer=STTServiceStream__pb2.STTMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sttstream.STTStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class STTStreamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientSend(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/sttstream.STTStreamService/ClientSend',
            STTServiceStream__pb2.StatusMessage.SerializeToString,
            STTServiceStream__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerSend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sttstream.STTStreamService/ServerSend',
            STTServiceStream__pb2.SubscribeRequest.SerializeToString,
            STTServiceStream__pb2.STTMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
